## Вычисления с помощью Numpy

### Задание 1

Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [9]:
import numpy as np

In [11]:
a = np.array([[1, 6], 
             [2, 8],
             [3, 11],
             [3, 10],
             [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [13]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

### Задание 2

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [14]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [15]:
a_centered_sp = np.dot(a_centered[0], a_centered[1])
a_centered_sp

0.960000000000001

In [19]:
a.shape[0]

5

In [18]:
a_centered_sp/a.shape[0]

0.1920000000000002

### Задание 4

В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [25]:
a_cov = np.cov(m = a.transpose())[0][1]
a_cov

2.0

# Работа с данными в Pandas

## Задание 1 

Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:  
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].


In [26]:
import pandas as pd

In [111]:
 first_data_frame = pd.DataFrame(
     {
         'author_id': [1, 2, 3],
         'author_name': ['Тургенев', 'Чехов', 'Островский']
     },
     columns= ['author_id', 'author_name']
 )
first_data_frame

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [42]:
book_data_frame = pd.DataFrame(
    {
        'author_id': [1, 1, 1, 2, 2, 3, 3],
        'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 
                       'Гроза', 'Таланты и поклонники'],
        'price': [450, 300, 350, 500, 450, 370, 290]
    },
    columns= ['author_id', 'book_title', 'price']
) 
book_data_frame

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

### Задание 2

Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

In [113]:
autrhors_price = pd.merge(first_data_frame, book_data_frame, 
                          on ='author_id', 
                          how = 'inner')
autrhors_price 

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

### Задание 3

Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [114]:
top5 = autrhors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

### Задание 4 

Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.


In [105]:
[autrhors_price.iloc[:, 1]]

[0      Тургенев
 1      Тургенев
 2      Тургенев
 3         Чехов
 4         Чехов
 5    Островский
 6    Островский
 Name: authron_name, dtype: object]

In [161]:
sorted(list(autrhors_price['author_name'].unique()))

['Островский', 'Тургенев', 'Чехов']

In [163]:
sorted(list(autrhors_price.groupby('author_name')['price'].max()))

[370, 450, 500]

In [164]:
sorted(list(autrhors_price.groupby('author_name')['price'].min()))

[290, 300, 450]

In [165]:
sorted(list(autrhors_price.groupby('author_name')['price'].mean()))

[330.0, 366.6666666666667, 475.0]

In [168]:
authors_stat = pd.DataFrame(
    {
        'author_name': sorted(list(autrhors_price['author_name'].unique())),
        'min_price': sorted(list(autrhors_price.groupby('author_name')['price'].min())),
        'max_price': sorted(list(autrhors_price.groupby('author_name')['price'].max())),
        'mean_price': sorted(list(autrhors_price.groupby('author_name')['price'].mean())),
    },
    columns= ['author_name', 'min_price', 'max_price', 'mean_price']
)
authors_stat

author_name  min_price  max_price  mean_price
0  Островский        290        370  330.000000
1    Тургенев        300        450  366.666667
2       Чехов        450        500  475.000000